CREATE TABLE role(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(20) NOT NULL
);

CREATE TABLE player(
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  pseudo VARCHAR(30) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  cookie BIGINT UNSIGNED DEFAULT 0,
  multiplicateur BIGINT UNSIGNED DEFAULT 1,
  role_id INT UNSIGNED,
  FOREIGN KEY (role_id) REFERENCES role(id)
);

CREATE TABLE upgrade (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  cout BIGINT UNSIGNED NOT NULL,
  multiplicateur DOUBLE NOT NULL,
  image_url VARCHAR(255)
);

CREATE TABLE achat (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  id_player BIGINT UNSIGNED NOT NULL,
  id_upgrade BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (id_player) REFERENCES player(id),
  FOREIGN KEY (id_upgrade) REFERENCES upgrade(id)
);

INSERT INTO role (name) VALUES ('admin'), ('joueur');